server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: INVESTMENT-SERVICE
          uri: lb://INVESTMENT-SERVICE
          predicates:
            - Path=/investments/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: FRONTEND-SERVICE
          uri: lb://FRONTEND-SERVICE
          predicates:
            - Path=/*

