apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
spec:
  selector:
    matchLabels:
      app: investment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
        - name: investment-service
          image: venenium/investmentservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: investment-service
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  selector:
    app: investment-service
  ports:
    - protocol: "TCP"
      port: 9001 # The port that the service is running on in the cluster
      targetPort: 9001 # The port exposed by the service
